# Config enxuta de memória — build leve, sem estourar RAM (e NUNCA emulador).
org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.workers.max=2
org.gradle.parallel=false
org.gradle.caching=true
kotlin.daemon.jvmargs=-Xmx1024m
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.java.home=/home/vianna/.gradle/jdks/eclipse_adoptium-17-amd64-linux.2
